config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root :to => 'pages#home'

  resources :users 
  resources :exercises
  resources :routines
  resources :workouts
  resources :public, :only => [:index, :show]
  resources :muscles

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
    has_many :workouts
    has_and_belongs_to_many :muscles
end

app/models/muscle.rb
class Muscle < ApplicationRecord
    has_and_belongs_to_many :exercises
end

app/models/routine.rb
class Routine < ApplicationRecord
    has_many :workouts
    belongs_to :user, :optional => true
    accepts_nested_attributes_for :workouts
end

app/models/user.rb
class User < ApplicationRecord
    has_many :routines
    has_many :workouts
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :user, :optional => true
    belongs_to :exercise, :optional => true
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :check_for_login
  
  def muscle_checker num
    m = Muscle.all
    m = m.map {|muscle| muscle.id.to_s}
    m & num
  end

  def index
    @exercises = Exercise.all
  end

  def new
    @exercise = Exercise.new
    @muscles = Muscle.all
  end

  def create
    exercise = Exercise.create exercise_params
    if !params[:muscle].nil?
      muscle_groups = muscle_checker params[:muscle] 
      exercise.muscles.clear
        muscle_groups.each do |n|
          muscle = Muscle.find [n]
          exercise.muscles << muscle
        end
    else
      exercise.muscles.clear
    end
    redirect_to exercise
  end

  def edit
    @exercise = Exercise.find params[:id]
    @muscles = Muscle.all
  end

  def update
    exercise = Exercise.find params[:id]
    if !params[:muscle].nil?
      muscle_groups = muscle_checker params[:muscle] 
      exercise.muscles.clear
        muscle_groups.each do |n|
          muscle = Muscle.find [n]
          exercise.muscles << muscle
        end
    else
      exercise.muscles.clear
    end
    exercise.update exercise_params
    redirect_to exercise 
  end

  def show
    @exercise = Exercise.find params[:id]
    @muscles = @exercise.muscles
  end

  def destroy
    exercise = Exercise.find params[:id]
    if @current_user.admin?
      exercise.destroy
      redirect_to exercises_path
    else 
      redirect_to exercise
    end
  end

  private
  def exercise_params
    params.require(:exercise).permit(:name, :image, :youtube, muscles_attributes: [:name, :image])
  end
end

app/controllers/muscles_controller.rb
class MusclesController < ApplicationController
  before_action :check_for_login

  def index
    @muscles = Muscle.all
  end

  def new
    @muscle = Muscle.new
  end

  def create
    muscle = Muscle.create muscle_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      muscle.image = req["public_id"]
    end
    muscle.update_attributes(muscle_params)
    muscle.save
    redirect_to muscle 
  end

  def edit
    @muscle = Muscle.find params[:id]
  end

  def update
    muscle = Muscle.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      muscle.image = req["public_id"]
    end
    muscle.update_attributes(muscle_params)
    muscle.save
    redirect_to muscle
  end

  def show
    @muscle = Muscle.find params[:id]
  end

  def destroy
    muscle = Muscle.find params[:id]
    if @current_user.admin?
      muscle.destroy
      redirect_to muscles_path
    else 
      redirect_to muscle
    end
  end

  private
  def muscle_params
    params.require(:muscle).permit(:name, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def index
        @routines = Routine.all
    end

    def show
        @routine = Routine.find params[:id]
        @workouts = @routine.workouts
        @check = @workouts.collect(&:sets)
    end

end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :check_for_login
  
  def index
    @routines = @current_user.routines
  end

  def new
    @routine = Routine.new
    @routine.workouts.build
  end

  def create
    routine = Routine.create routine_params
    workout = routine.workouts.build
    @current_user.routines << routine
    workout.sets = params[:workouts][:sets]
    workout.reps = params[:workouts][:reps]
    workout.exercise_id = params[:workouts][:exercise_id]
    workout.save
    routine.update routine_params
    routine.workouts<<workout
    redirect_to routines_path
  end

  def edit
    @routine = Routine.find params[:id]
    @routine.workouts.build
    workouts = @current_user.workouts
  end

  def update
    routine = Routine.find params[:id]
    workout = routine.workouts.build
    workout.sets = params[:workouts][:sets]
    workout.reps = params[:workouts][:reps]
    workout.exercise_id = params[:workouts][:exercise_id]
    workout.save
    routine.update routine_params
    routine.workouts<<workout
    redirect_to routine
  end

  def show
    @routine = Routine.find params[:id]
    @workouts = @routine.workouts
    @check = @workouts.collect(&:sets)
  end

  def destroy 
    routine = Routine.find params[:id]
    routine.destroy
    redirect_to routines_path
  end

  private
  def routine_params
    params.require(:routine).permit(:title, workouts_attributes: [:sets, :reps, :exercise_id])
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Sorry, login failed"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @user.image = req["public_id"]
    end
    @user.update_attributes(user_params)
    @user.save
  end

  def edit 
    if params[:id].to_i == @current_user.id || @current_user.admin? 
      @user = User.find params[:id] 
    else 
      redirect_to user_path
    end
  end

  def update
    user = User.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.image = req["public_id"]
    end
    user.save
    redirect_to user
  end

  def show
    @user = User.find params[:id]
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :check_for_login

    def index
        @workouts = Workout.all
    end

    def new
        @workout = Workout.new
    end
    
    def create
        workout = Workout.new workout_params
        @current_user.workouts << workout
        redirect_to workouts_path
    end

    def edit
        @workout = Workout.find params[:id]
    end
    
    def update
        workout = Workout.find params[:id]
        workout.update workout_params
        redirect_to "/routines/#{workout[:routine_id]}" 
    end

    def destroy 
        workout = Workout.find params[:id]
        workout.destroy
        redirect_to "/routines/#{workout[:routine_id]}" 
      end

    private
    def workout_params
        params.require(:workout).permit(:sets, :reps, :name, :exercise_id, :routine_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/muscle_helper.rb
module MuscleHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/routine_helper.rb
module RoutineHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/muscles/_form.html.erb
<%= form_for(@muscle, :html => {:multipart => true}) do |f| %>
    <div class="form">
    <%= f.label :name %>
    <%= f.text_field :name, :required => true %>

    <%= f.label :Image %>
    <%= f.cl_image_upload :image %>

    <%= f.submit "Update Muscle" %>
    </div>
<% end %>

app/views/muscles/edit.html.erb
<h1>Edit Muscle Group</h1>

<%= render :partial => 'form' %>

app/views/muscles/index.html.erb
<h1>List of Muscle Groups</h1>

<div class="list">
<% @muscles.each do |muscle| %>
    <ul>
        <%= link_to muscle.name, muscle %>
    </ul>
<% end%>
</div>

<div class="controls">
<h4><%= link_to "Add Muscle", new_muscle_path %></h4>
</div>

app/views/muscles/new.html.erb
<h1>New Muscle Group</h1>

<%= render :partial => 'form' %>

app/views/muscles/show.html.erb
<h1> <%= @muscle.name %></h1>
<% if @muscle.image.present? %>
     <%= cl_image_tag(@muscle.image, :class => "muscle")%>
<% end %>
<h2>Exercises that train <%= @muscle.name %>: </h2>
<div class="list">
<% @muscle.exercises.each do |exercise| %>
    <ul>
    <p> <strong> <%= link_to exercise.name, exercise %> </strong> </p>
    </ul>
<% end %>
</div>


<div class="controls">
    <%= link_to "Edit Muscle", edit_muscle_path(@muscle) %>
    <%= link_to 'Delete Muscle', @muscle, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
</div>

app/views/routines/_form.html.erb
<%= form_for @routine do |f| %> 
    <%= f.label :title %>:
    <%= f.text_field :title %>
    <h3>Add Workout</h3>
    <%= render :partial => 'workout_fields' %> 
    <br>
    <div class="submit">
    <%= f.submit "Create Routine" %>
    </div>
<% end %>

app/views/routines/_workout_fields.html.erb
<div class="workoutform">
<%= fields_for :workouts do |builder| %>
    <%= builder.label :sets %>:
    <%= builder.number_field :sets, :required => true %>
    <%= builder.label :reps %>:
    <%= builder.number_field :reps, :required => true %>
    <%= builder.label :exercise_id %>:
    <%= builder.select :exercise_id, Exercise.pluck(:name, :id) %>
<% end %>
</div>

app/views/routines/edit.html.erb
<h1> Update Routine </h1>
    <%= form_for @routine do |f| %> 
        <%= f.label :title %>:
        <%= f.text_field :title %>
<h3>Add Workout</h3>
    <%= render :partial => 'workout_fields' %>  
    <br>
    <%= f.submit "Add to Routine" %>
<% end %>

app/views/routines/index.html.erb
<h1>My Routines</h1>
<div class="container">
<% @current_user.routines.each do |routine| %>
    <div class="card" >
        <h2><%= routine.title %></h2>
        <div class="cardimage">
        <% if @current_user.image.present?%>
            <%= link_to cl_image_tag(@current_user.image), routine %>
        <% else %>
            <%= link_to image_tag("default.png"), routine %>
        <% end %>
        </div>
        <br>
    </div>
<% end %>
<% if @current_user.routines.empty? %>
    <h2>No routines!</h2>
<% end%>

<div class="controls">
<%= link_to "Create Routine", new_routine_path %>
</div>

</div>

app/views/routines/new.html.erb
<h1>New Routine</h1>

<%= form_for @routine do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit %>
<% end %>

app/views/routines/show.html.erb
<h1><%= @routine.title %></h1>
    <% if @routine.workouts.present? %>
        <% @workouts.each do |workout| %>
            <div class="routinedisplay">
            <div class="workoutlist">
             <strong><%= workout.sets %> </strong> sets of 
             <strong><%= workout.reps %> </strong> reps of
             <strong><%= link_to "#{workout.exercise.name.pluralize}", "/exercises/#{workout.exercise_id}" %> </strong> 
        </div>
        <div class="routinecontrols">
            <%= link_to "Edit", edit_workout_path(workout) %>
            <%= link_to "Remove", workout, :method => 'delete', :data => {:confirm => "Delete workout?"} %>
        </div>
        </div>
        <% end %>
    <% end %>

<div class="controls">
    <%= link_to "Add to Routine", edit_routine_path(@routine) %>
    <%= link_to 'Delete Routine', @routine, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
</div>

app/views/users/edit.html.erb
<h1>Editing: <%= @user.email %></h1>

<% if @user.errors.any? %>
<div class="form">
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
        <%= msg %>
        <% end %>
    </ol>
</div>
<% end %>

<div class="form">
<%= form_for(@user, :html => {:multipart => true}) do |f| %>
    <%= f.label :Profile_picture %>
    <%= f.cl_image_upload :image %>

    <%= f.submit "Update Details" %>
<% end %>
</div>

app/views/users/index.html.erb
<h1>All users</h1>
<h2><%= @users.count %> registered users</h2>
<div class="list">
<ul>
    <% @users.each do |user| %>
        <p>
        <% if user.admin? %>
            <%= image_tag("admin.png", :class => "icon")%>
        <% else%>
            <%= image_tag("user.png", :class => "icon")%>
        <% end%>
        <%= link_to "#{user.email}", user %> 
        </p>
    <% end %>
</ul>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
    <h2>
        <% @user.errors.full_messages.each do |msg| %>
        <%= msg %> <br>
        <% end %>
    </h2>
<% end %>
<div class="form">
<%= form_for(@user, :html => {:multipart => true}) do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email, :required => true %>

    <%= f.label :password %>
    <%= f.password_field :password, :required => true %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :required => true %>

    <%= f.label :Profile_Picture %>
    <%= f.cl_image_upload :image %>
    
    <%= f.submit "Register" %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="user_image">
    <% if @user.image.present? %>
        <%= cl_image_tag(@user.image) %>
    <% else %>
        <%= image_tag("default.png")%>
    <% end %>
</div>

<div class="user_name">
    <h2>
        <%= @user.email %>'s' Page
    </h2>
    
</div>

<div class="user_facts">
<h2>Facts</h2>
    <ul>
        <li>has made <strong><%= @user.routines.count  %></strong> Routines </li>
    </ul>
</div>

<div class="controls">
    <%= link_to "Edit User", edit_user_path %>
</div>

app/views/workouts/_form.html.erb
<div class="workoutform">
<%= form_for @workout do |f| %> 
    <%= f.label :sets %>:
    <%= f.number_field :sets %>

    <%= f.label :reps %>:
    <%= f.number_field :reps %>

    <%= f.label :exercise_id %>:
    <%= f.select :exercise_id, Exercise.pluck(:name, :id) %>
    <%= f.submit "Submit", :id => "button" %>
<% end %>
</div>

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>

<%= render :partial => 'form' %>

app/views/workouts/index.html.erb
<h1>My Workouts</h1>

<% @current_user.workouts.each do |workout| %>
    <ul>
        <li> 
            <%= link_to "#{workout.name}", "/exercises/#{workout.exercise_id}" %> 
         </li>
    </ul>
<% end %>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render :partial => 'form' %>