config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root :to => 'pages#home'

  resources :users 
  resources :exercises
  resources :routines
  resources :workouts
  resources :public, :only => [:index, :show]
  resources :muscles

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
    has_many :workouts
    has_and_belongs_to_many :muscles
end

app/models/muscle.rb
class Muscle < ApplicationRecord
    has_and_belongs_to_many :exercises
end

app/models/routine.rb
class Routine < ApplicationRecord
    has_many :workouts
    belongs_to :user, :optional => true
    accepts_nested_attributes_for :workouts
end

app/models/user.rb
class User < ApplicationRecord
    has_many :routines
    has_many :workouts
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :user, :optional => true
    belongs_to :exercise, :optional => true
end

app/controllers/muscles_controller.rb
class MusclesController < ApplicationController
  before_action :check_for_login

  def index
    @muscles = Muscle.all
  end

  def new
    @muscle = Muscle.new
  end

  def create
    muscle = Muscle.create muscle_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      muscle.image = req["public_id"]
    end
    muscle.update_attributes(muscle_params)
    muscle.save
    redirect_to muscle 
  end

  def edit
    @muscle = Muscle.find params[:id]
  end

  def update
    muscle = Muscle.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      muscle.image = req["public_id"]
    end
    muscle.update_attributes(muscle_params)
    muscle.save
    redirect_to muscle
  end

  def show
    @muscle = Muscle.find params[:id]
  end

  def destroy
    muscle = Muscle.find params[:id]
    if @current_user.admin?
      muscle.destroy
      redirect_to muscles_path
    else 
      redirect_to muscle
    end
  end

  private
  def muscle_params
    params.require(:muscle).permit(:name, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def index
        @routines = Routine.all
    end

    def show
        @routine = Routine.find params[:id]
        @workouts = @routine.workouts
        @check = @workouts.collect(&:sets)
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Sorry, login failed"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @user.image = req["public_id"]
    end
    @user.update_attributes(user_params)
    @user.save
  end

  def edit 
    if params[:id].to_i == @current_user.id || @current_user.admin? 
      @user = User.find params[:id] 
    else 
      redirect_to user_path
    end
  end

  def update
    user = User.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.image = req["public_id"]
    end
    user.save
    redirect_to user
  end

  def show
    @user = User.find params[:id]
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/muscle_helper.rb
module MuscleHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/routine_helper.rb
module RoutineHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workout Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body> 
    <nav>
    <% if @current_user && @current_user.admin? %>
        <%= link_to "All users", users_path %>
    <% end%>
        <%= link_to "Home", root_path %>
    <% if @current_user.present? %>
        <%= link_to "Exercises", exercises_path %>
        <%= link_to "Muscles", muscles_path %>
        <%= link_to "My Routines", routines_path %>
        <%= link_to "All Routines", public_index_path %>
        <%= link_to "Logout", login_path, :method => 'delete' %>
        <%= link_to "#{@current_user.email}", user_path(@current_user) %>
        <% if @current_user.admin? %>
            <%= image_tag("admin.png", :class => "icon")%>
        <% else%>
            <%= image_tag("user.png", :class => "icon")%>
        <% end%>
    <% else  %>
        &nbsp; &nbsp;|&nbsp;&nbsp;
        <%= link_to "Login", login_path %>
        <%= link_to "Register", new_user_path %>
    <% end %>
    </nav>
      <div class="container">
        <%= yield %>
        <div class="back">
          <%= link_to 'Go Back', :back %>
        </div>
      </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome</h1>


<% if @current_user.present? %>
    <%= link_to image_tag("user_home.png", :class => "home"), routines_path %>
    <p>Time to make some gains</p>
<% else %>
    <%= link_to image_tag("home.png", :class => "home"), login_path %>
    <p>Ready to begin?</p>
<% end %>